Se agregan errores de PHP a log.

diff --git a/.github/workflows/cd.yml b/.github/workflows/cd.yml
--- a/.github/workflows/cd.yml
+++ b/.github/workflows/cd.yml
@@ -46,8 +46,11 @@ jobs:
       - name: Build with Vite
         run: npm run build
 
+      - name: Enable error logging
+        run: echo 'error_log = /tmp/php_errors.log' >> ~/.phpenv/versions/$(php -r "echo PHP_MAJOR_VERSION.'.'.PHP_MINOR_VERSION;")/etc/php.ini
+
       - name: Start PHP server
-        run: php -d display_errors=1 -S 127.0.0.1:9000 public/index.php &
+        run: php -d display_errors=1 -d error_reporting=E_ALL -S 127.0.0.1:9000 public/index.php &
 
       - name: Download static HTML with wget
         run: |
@@ -57,6 +60,9 @@ jobs:
                --directory-prefix=output --no-host-directories \
                --restrict-file-names=windows \
                http://127.0.0.1:9000/ || [[ $? == 8 ]]
+
+      - name: Show PHP error log
+        run: cat /tmp/php_errors.log || true
 
       - name: Deploy to GitHub Pages
         uses: JamesIves/github-pages-deploy-action@v4
